php artisan make:model Category
php artisan make:model Product
php artisan make:model ProductCart
php artisan make:model ProductDetail
php artisan make:model ProductReview
php artisan make:model ProductSlider
php artisan make:model ProductWish
php artisan make:model Profile
php artisan make:model User